### ISSUE TITLE
BookService: Missing endpoints

### ISSUE THREAD

**Issue by ManasesLovera** [ManasesLovera/bookStore#18]
### Endpoints that need to be created for the API:

1. Delete book
2. Add stocks to a book by id and amount
3. Remove/reduce stocks to a book by id and amount
4. Update book

- Note: Everytime you add and remove from stock, or update the data, you must also change the UpdateAt property with DateTime.UtcNow.

**Comment by ManasesLovera** [comment]
Pull request from your branch to the dev branch, please comment to this issue if you'd like to complete this task.

**Comment by Wil-JsDev** [comment]
Working on it

**Comment by ManasesLovera** [comment]
DONE!
